dist: trusty
language: cpp
sudo: false


notifications:
  email:
    on_success: never
    on_failure: always


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

#    - os: linux
#      compiler: clang++
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-5.0
#          packages:
#            - clang-5.0
#            - llvm-5.0-dev
#      env:
#        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: osx
      compiler: clang++
      env:
        - COMPILER=clang++ V='Apple LLVM 6.0'  # Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
        - COMP=clang


before_install:
  - eval "${MATRIX_EVAL}"


before_script:
- cd src
- mkdir build
- cd build
- cmake ..


script:
- make
- ./tests/unittest
